name: Bug Report
description: File a bug report
title: "Bug: "
labels: bug

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps To Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: It should...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Output
      description: Please enter any relevant output as plain text.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Please provide any additional details about the bug and its environment.
      placeholder: |
        - Tell us about where you are seeing the problem.
          - Device
          - Operating System
          - Browser
        - Do you have relevant screenshots?
        - Do you have any other information that might be helpful?
